bootstrap_errors_list:  
programs with errors: []

rename_me_errors_list:  
test igrf.py: small change in output files.  someone else must debug.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 647, in complete_igrf_test
    raise Exception('small change in output files.  someone else must debug')

test tdt_magic.py: TDT_magic pull up gui window and can not be tested.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1271, in complete_TDT_magic_test
    raise Exception('TDT_magic pull up gui window and can not be tested')

test HUJI_magic.py: initializing variables were removed.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Rename_me.py", line 1281, in complete_HUJI_magic_test
    raise NameError('initializing variables were removed')

programs with errors: ['test igrf.py', 'test tdt_magic.py', 'test HUJI_magic.py']

random_errors_list:  
programs with errors: []

extra_output_errors_list:  
test IODP_csv.py: Wrong output -- output list did not match correct_output_list -- running IODP_csv_magic.py.  
Traceback below: 
  File "/Users/nebula/Python/PmagPy/Command_line_Tests/error_logging.py", line 27, in go_through
    v()
  File "Extra_output.py", line 439, in complete_IODP_csv_magic_test
    IODP_csv.check_file_output(out3, ref3, "correct")
  File "Extra_output.py", line 135, in check_file_output
    self.check_list_output(out, ref)
  File "Extra_output.py", line 93, in check_list_output
    raise NameError("Wrong output -- output list did not match correct_output_list -- running " + str(self.name))

programs with errors: ['test IODP_csv.py']

